spring.application.name=fitness_app


# Base configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_app?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=alex2007@1234
logging.level.org.hibernate.persister.entity=ERROR
spring.jpa.open-in-view=false

#PATCH,PUT REQUESTS
spring.mvc.hiddenmethod.filter.enabled=true


#User properties
users.defaultUser.username=alex2007
users.defaultUser.password=1234
users.defaultUser.country=BULGARIA
users.testField=Test field 123
